# dist: xenial

language: python

sudo: false

cache: pip

matrix:
    include:
      - python: 2.7
        env: TOXENV=py27
      - python: 3.4
        env: TOXENV=py34
      - python: 3.5
        env: TOXENV=py35
      - python: 3.6
        env: TOXENV=py36
      - python: 3.7-dev
        env: TOXENV=py37
    # This is broken on travis as of 2019/03/12
    # - python: pypy
    # env: TOXENV=pypy

# build libyaml
before_script:
  - >-
    cd /tmp
    && git clone https://github.com/yaml/libyaml.git libyaml
    && cd libyaml
    && git reset --hard 0.2.2
    && ./bootstrap
    && ./configure
    && make
    && make test-all
    && sudo make install
    && sudo ldconfig
    && cd "$TRAVIS_BUILD_DIR"

install: pip install cython tox

script: tox
